### ISSUE TITLE
check pixel mapping in the reader

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/protozfitsreader#15]
This is an issue requested by @calispac, I just write it down.

Currently the adc samples of our 1296 pixels in our zfits files are written in some specific order. This order is also stored in the file, so the reader can (and does) return the adc samples not in the order it is written into the file, but in the order of pixel_ids.

So the user of the reader does not know in which order the adc samples are stored. 

---

Cyril proposes to inform the user, if the order in the file changes with respect to the order which was used e.g. in the 100evts. example file delivered with digicam pipe.

**Comment by dneise** [comment]
My personal opinion is different.

I think this pixel order is nicely hidden away. If it changes the reader still works and the user still gets the correct information. 

I understand that the order should not change, and if it suddenly does, this might be a hint for a problem. 
But it might also be, that the people who write the files change the order on purpose.

Then all users get a warning, until we find time to change this check. 

Not sure if this is worth it.

**Comment by calispac** [comment]
Actually I am wondering if the pixel ids order given by the Zfits file is always correct? Is this given by the user when the writer is started @Etienne12345?

**Comment by dneise** [comment]
What do you mean by "correct"? Do you mean it is possible that the waveforms are stored in "some-order" and the pixel-ids are stores in "another-order". And then the user gets something, which is totally unusable?

**Comment by Etienne12345** [comment]
Yes, the mapping is -always- correct. Not given by the user, but embedded in the raw data itself. In case a file would not have the correct mapping (e.g. because the data-taker used a wrong command line to start the camera server), then I have a program that fixes the mapping. 

As far as I can remember, we had discussed this and had agreed that the analysis software should have not idea about how to manipulate the mapping, which would suggest that this re-mapping code should be gotten rid of entirely.

**Comment by dneise** [comment]
> As far as I can remember, we had discussed this and had agreed that the analysis software should have not idea about how to manipulate the mapping, which would suggest that this re-mapping code should be gotten rid of entirely.

Oh .. I have not been aware of that discussion, :-( ... sorry

**Comment by calispac** [comment]
> Yes, the mapping is -always- correct. Not given by the user, but embedded in the raw data itself. In case a file would not have the correct mapping (e.g. because the data-taker used a wrong command line to start the camera server), then I have a program that fixes the mapping.

Ok, yes you are write. so lets forget about maps in digicampipe

**Comment by Etienne12345** [comment]
The reasonning was that this should be capable to handle several cameras with different mapping anyways. The analysis software should remain the same. 
Also, at some point we might do zero-suppression or other pixels-trimming: the analysis software should be insensitive to that also.

**Comment by dneise** [comment]
I am not sure I understand this discussion. 

> Yes, the mapping is -always- correct. Not given by the user, but embedded in the raw data itself. 

From this I understand, the reader does never have to warn a user, that some file uses probably a wrong mapping. 

> In case a file would not have the correct mapping (e.g. because the data-taker used a wrong command line to start the camera server), then I have a program that fixes the mapping.

From this I understand the opposite: It might happen that data-taker makes a mistake, which results in an **inconsistent** mapping. Do I understand that correctly?

**Comment by calispac** [comment]
> From this I understand the opposite: It might happen that data-taker makes a mistake, which results in an inconsistent mapping. Do I understand that correctly?

Yes. but we cannot handle data-taker mistake in protozfitsreader right? If there is a warning shouldn't it be at the data taking stage ?

**Comment by dneise** [comment]
Yes, I totally agree! perfect argument, thanks.

**Comment by Etienne12345** [comment]
Yes, you understood everything correctly. Yes a files can be messed up, but the analysis software should not take care of this at all: it is the duty of the ingest pipeline / data taker to put correct files into the archive.

**Comment by dneise** [comment]
perfect. I like this spearation of concerns a lot.

So I will now remove this `pixel_remap` array from the code, which is still there, but was never used to my knowledge since ~Nov.2017

**Comment by calispac** [comment]
Is there a way to treat patch_indices as well from the zfits file? I mean is there a field in the file?

**Comment by Etienne12345** [comment]
What does that mean ? Are you asking if there is a flag "my indices are correct" in the file ?

**Comment by calispac** [comment]
> What does that mean ? Are you asking if there is a flag "my indices are correct" in the file ?

Sorry, I mean is there a field in the zfits file containing the mapping for the patch_ids as there is now a field in the zfits file for the pixel_ids?

Or is there a "logical way" to pass from pixel_ids to patch_ids?

**Comment by Etienne12345** [comment]
Ah, right. No, there is not. Agreed it is somewhat inconsistent, but reason is as follow:
- pixels do have pixels IDs, because we wanna be flexible with the pixels (multiple cameras / pixels trimming / ...)
- patches data is somewhat "digicam internal" and won't be used either by the common analysis nor other cameras. so in that sense, we are simply "dumping the data from the camera". Ok we do some kind of reshuffling in the camera server, but that's all hard coded. If we would have been the only camera and operating "a la fact" we would have probably done the same for the pixels.
