### ISSUE TITLE
Can patch mapping be derived from camera config file instead of hard coded?

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/protozfitsreader#17]
There are two mapping needed at the moment in this reader, called:
 * [PATCH_ID_INPUT](https://github.com/cta-sst-1m/protozfitsreader/blob/master/protozfitsreader/__init__.py#L101) and
 * [PATCH_ID_OUTPUT](https://github.com/cta-sst-1m/protozfitsreader/blob/master/protozfitsreader/__init__.py#L132)

Instead of having these hardcoded, can we generate them somehow? 
Maybe from this file?

https://github.com/cta-sst-1m/CTS/blob/master/config/camera_config.cfg

**Comment by calispac** [comment]
I don't think so. This is the pixel_id to any id mapping...
e.g. patch_y is in pixel_z.

PATCH_ID_INPUT/OUTPUT refers to the order from which they PATCH_IDs are "written"

**Comment by dneise** [comment]
Ah ... I see. Thank you
