### ISSUE TITLE
__len__() function for ZFile

### ISSUE THREAD

**Issue by calispac** [cta-sst-1m/protozfitsreader#30]
I think one should have a `__len__()` function for the `ZFile` class.

The function should return `self.numrows`. That way one can access easily how much events are contained in the file. It is also quiet useful for progress bars with the `tqdm` module

**Comment by dneise** [comment]
The `Table` class has `__len__` defined, so when iterating over the "Events" `Table` everything should be fine,

**Comment by dneise** [comment]
https://github.com/cta-sst-1m/protozfitsreader/blob/156e865e45704ca73a3a4ab5929084c2eb7e0c13/protozfits/simple.py#L79-L82
