### ISSUE TITLE
Install problem: ImportError: libpython3.6m.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/protozfitsreader#31]
This issue was raised in https://github.com/cta-observatory/ctapipe/issues/698 by @IsidroAguadoRuesga.

I just copy it here:

---

I have start to work in ctapipe SW development few weeks ago; my work shall be focused in LST DL0 files reading. So, I have installed the protozfits SW following the steps you recommend in the post from 18 of April/2018. 

The installation was made downloading from https://github.com/cta-sst-1m/protozfitsreader . No errors were reported in the installation process but when I try to use, it fails with the following error message:

```
>>> from protozfits import SimpleFile
Traceback (most recent call last):
File "", line 1, in
File "/usr/users/iaguado/CTA_Work/SW/ZFits SW for ctapipe/protozfitsreader/protozfits/init.py", line 2, in from .digicam import File as DigicamFile
File "/usr/users/iaguado/CTA_Work/SW/ZFits SW for ctapipe/protozfitsreader/protozfits/digicam.py", line 6, in from . import rawzfitsreader
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

The installation was made with setup.py build and setup.py commands, but with pip installation process the same error is obtained. The error remains, either running python from protozfitsreader directory or moving down to protozfits subdirectory. Also, pytest command produces the same error.
    Any idea of what is wrong or missing?
    Thank you in advance,

PD: I am working on Linux with python 3.6 from ctapipe environment (cta-dev2) that was previously installed with anaconda.

**Comment by dneise** [comment]
I would recommend to remove this installation that you did before and reinstall it as explained in the README:

https://github.com/cta-sst-1m/protozfitsreader#installation

Could you do that and then try again?

**Comment by IsidroAguadoRuesga** [comment]
It works.
Only a tiny correction, it's necessary to install cython with numpy protobuf and astropy.
Also, I have installed from scratch with python 3.6 and also works. It takes me some more time but 
now I can compare the new environment with the old one, in order to  discover where the problem is.
Thank @dneise for your help.

**Comment by dneise** [comment]
Thank you for the feedback. I will add `cython` as a dependency.
