### ISSUE TITLE
SimpleFile now named File only --> ctapipe

### ISSUE THREAD

**Issue by dneise** [cta-sst-1m/protozfitsreader#40]
Since v1.0.2 `SimpleFile` is named `File` now. 

This has an impact on many Event Readers in ctapipe. We need to fix that asap, so ctapipe can always use the latest release.

**Comment by IsidroAguadoRuesga** [comment]
@dneise Keep in mind that its is necessary to update the README.md file:
      >>> from protozfits import SimpleFile
      >>> example_path = 'protozfits/tests/resources/example_9evts_NectarCAM.fits.fz'
      >>> file = SimpleFile(example_path)
It is not the most urgent issue but it will disorient, especially for new comers.
