### ISSUE TITLE
Problem on "import rawzfitsreader"

### ISSUE THREAD

**Issue by ekoume** [cta-sst-1m/protozfitsreader#45]
Dear all,
I installed Digicampipe like as describe in github and i got problem "import rawzfitsreader" on "from digicampipe.io import event_stream". The error answer is pasted below. Can someone help me?

```bash
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rawzfitsreader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rawzfitsreader'
>>> import protozfits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/__init__.py", line 2, in <module>
    from .digicam import File as DigicamFile
  File "/home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/digicam.py", line 6, in <module>
    from . import rawzfitsreader
ImportError: /home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5IFits14listPastTablesB5cxx11Ev
>>> 
```

**Comment by Etienne12345** [comment]
Hello, 

well that's unfortunate... Let's investigate. Some questions first:
- which command did you use exactly to do the installation ?
- could you please run "ldd /home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so" ?

**Comment by calispac** [comment]
@jurysek I think you had a similar issue.

**Comment by Etienne12345** [comment]
From a "cold start" point of view, it looks it uses an older version of the CamerasToACTL libs on your system: did you by any chance compile CamerasToACTL on your system ? 
In any case ldd should tell use which lib is being used.

**Comment by ekoume** [comment]
----> Procedure of installation
             -->git clone https://github.com/cta-sst-1m/digicampipe
             -->conda env create -f digicampipe/environment.yml
             -->conda env update -f digicampipe/environment.yml
             -->source activate digicampipe
             -->pip install -e digicampipe
             -->python setup.py develop in my digicampipe directory
             --> digicam-view "my_hdf5_file"

------->I run "ldd /home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so"

```bash
ldd /home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffe53da1000)
        libZFitsIO.so => /home/sterody/.local/lib/python3.5/site-packages/libZFitsIO.so (0x00007efe0ccce000)
        libstdc++.so.6 => /home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/../../../libstdc++.so.6 (0x00007efe0c994000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efe0c664000)
        libgcc_s.so.1 => /home/sterody/anaconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/../../../libgcc_s.so.1 (0x00007efe0c452000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efe0c232000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efe0be6b000)
        libACTLCore.so => /home/sterody/.local/lib/python3.5/site-packages/libACTLCore.so (0x00007efe0bbd9000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efe0b9bd000)
        libzmq.so.3 => /home/sterody/.local/lib/python3.5/site-packages/libzmq.so.3 (0x00007efe0b777000)
        libprotobuf.so.9 => /home/sterody/.local/lib/python3.5/site-packages/libprotobuf.so.9 (0x00007efe0b45f000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563c4fef0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007efe0b257000)

```

**Comment by calispac** [comment]
FWY this is what I get with `ldd`:

```bash
(digicampipe) alispach@alispach-ThinkPad-X1-Carbon-4th:~$ ldd /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fff33e64000)
	libZFitsIO.so => /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/libZFitsIO.so (0x00007f06fcd82000)
	libstdc++.so.6 => /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/../../../libstdc++.so.6 (0x00007f06fca48000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f06fc73f000)
	libgcc_s.so.1 => /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/../../../libgcc_s.so.1 (0x00007f06fc52d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f06fc310000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f06fbf46000)
	libACTLCore.so => /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/libACTLCore.so (0x00007f06fbbd7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f06fb9bd000)
	libprotobuf.so.9 => /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/libprotobuf.so.9 (0x00007f06fb6ac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f06fd353000)
	libzmq.so.4 => /home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/libzmq.so.4 (0x00007f06fb45c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f06fb254000)

```

**Comment by calispac** [comment]
The instalation of the `protozfits` package is done while creating an anconda env. for digicampipe : 

https://github.com/cta-sst-1m/digicampipe/blob/e1aef74ba362ada3197ee1c68ba2364cac7ff975/environment.yml#L38

It is done in the "simple way". For the LD_LIBRARY_PATH I know it is still necessary for MacOS users. At least from what I have seen recently

**Comment by Etienne12345** [comment]
@calispac I have no idea what I am supposed to see in the link: could you maybe clarify ?

What @ekoume wrote as his installation procedure is certainly not "the simple way": would be great if I could understand where he too the instructions from so that I can remove them and leave only the instructions from the man page.

**Comment by calispac** [comment]
@Etienne12345 

>EDIT: Oh I think that I understand: you use teh .yml environnement to create the conda env. Only problem is that the package points to an outdated version of the package: I should update also this yml file at some point. I am not sure what is the simplest though: myself I
-create a conda environment

    do conda install protobuf
    do pip install

Yes that's how @ekoume  installed the protozfits package and some of the CameraToACTL project files were remaining on his machine from an old installation. 

Regarding using the latest protozfits realese @dneise was working on it at some point in this PR https://github.com/cta-sst-1m/digicampipe/pull/202

Maybe we should wait for the protozifts branch working_on_version_1_1 to be merged to finish this pull request

**Comment by jurysek** [comment]
HI everyone, I have the same issue and I installed the digicampipe in the same way how @ekoume did. There is my ldd output below. So, should I wait until the updated version of the package will be a part of the .yml environment?

```
(digicampipe) jakub@s122:~/ctasoft/digicampipe$ ldd /home/jakub/anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd5d1cc000)
	libZFitsIO.so => /home/jakub/.local/lib/python3.5/site-packages/libZFitsIO.so (0x00007f879f8a7000)
	libstdc++.so.6 => /home/jakub/anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/../../../libstdc++.so.6 (0x00007f879f56d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f879f1cf000)
	libgcc_s.so.1 => /home/jakub/anaconda3/envs/digicampipe/lib/python3.5/site-packages/protozfits/../../../libgcc_s.so.1 (0x00007f879efbd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f879ed9e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f879e9ad000)
	libACTLCore.so => /home/jakub/.local/lib/python3.5/site-packages/libACTLCore.so (0x00007f879e691000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f879e474000)
	libzmq.so.3 => /home/jakub/.local/lib/python3.5/site-packages/libzmq.so.3 (0x00007f879e226000)
	libprotobuf.so.9 => /home/jakub/.local/lib/python3.5/site-packages/libprotobuf.so.9 (0x00007f879df10000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f879fe64000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f879dd08000)

```

**Comment by Etienne12345** [comment]
Hello @jurysek, indeed: exact same issue as @ekoume. You can try to also remove the libraries from this directory, and see if it helps: updating to the latest, upcoming version of the package won't remove the crappy old libraries that you have on your system.

**Comment by ekoume** [comment]
Hello
It's working now for me. I erased all files of the folder "/home/sterody/.local/lib/python3.5/site-packages/". Then, i used commands:
-->mv digicampipe digicampipe_old
-->conda env remove -n digicampipe
-->git clone https://github.com/cta-sst-1m/digicampipe
-->conda env create -f digicampipe/environment.yml
-->conda env update -f digicampipe/environment.yml
-->source activate digicampipe
-->pip install -e digicampipe
-->python setup.py develop in my digicampipe directory
--> digicam-view "my_hdf5_file"

Thanks a lot at all.

**Comment by Etienne12345** [comment]
Great !

**Comment by jurysek** [comment]
The same works for me too. Thank you all!
