### ISSUE TITLE
Update reader to include latest data model modifications

### ISSUE THREAD

**Issue by sizun** [cta-sst-1m/protozfitsreader#62]
Hello. Could the reader be updated so that the new native charge fields in the [NectarCAM data model](https://forge.in2p3.fr/projects/cta/repository/changes/ACTL/CamerasToACTL/trunk/DataModel/R1_NectarCam.proto) can be read? Currently, it generates the following warnings:

`This column (10.8) is not in the available message description. You are probably using an outdated version of the zfits reader...

This column (10.9) is not in the available message description. You are probably using an outdated version of the zfits reader...`

**Comment by Etienne12345** [comment]
Hello Patrick, 

as requested a new, updated release was created with latest data model and ZSTD support, for both linux and osx. Please update your python module as follow:

pip install https://github.com/cta-sst-1m/protozfitsreader/archive/v1.5.0.tar.gz

Cheers, 

Etienne

**Comment by Etienne12345** [comment]
Requested was completed. If further problem occur please open a new issue.

**Comment by FrancaCassol** [comment]
Hi,

just a question before closing. I see that the new fields are:

```
optional DataModel.AnyArray      charges_gain1         = 8;  // HG
optional DataModel.AnyArray      charges_gain2         = 9;  // LG
 
```
 what are they supposed to contain and at which level are they filled? 

Thanks

**Comment by Etienne12345** [comment]
I have no idea: @sizun should know !

**Comment by sizun** [comment]
Thank you @Etienne12345 for the update. @FrancaCassol , the wayt we configure the front-end boards now, they send both waveforms and natively integrated charges. These two containers contain the high and low gain native charges respectively (they had been dropped when we switched to the R1 format).

**Comment by FrancaCassol** [comment]
Thanks for the explanation @sizun. 
Sorry, some other question. In order to correctly update the reader, which shape have these arrays? 
And, for curiosity, what makes them different from the  R1 waveform charge?

**Comment by sizun** [comment]
> In order to correctly update the reader, which shape have these arrays?
Each one is a 1d array of type uint16 and size npixels (npixels = 1855 for the full camera but less now). I guess that, for symmetry with the waveforms, the reader should expose them as a single 2d array of shape (ngains*npixels)?
> And, for curiosity, what makes them different from the R1 waveform charge?
They are only a diagnostic tool to detect issues with the FEBs. In theory they provide redundant information compared to the waveforms. Although, there may be a mode where the charge integration window is dynamic and does not correspond to the full readout window.

**Comment by FrancaCassol** [comment]
I see. Thanks very much @sizun 
I think we can close this issue.
